Second Refactor - science
m2lines/convection-parameterization-in-CAM pull request #43
Opened 2023-07-24 12:54 UTC by jatkinson1000

Second refactor of code from a scientific standpoint rather than the structural standpoint of #33 

Tasks (discussed in #41 ):
- [X] Remove `qn`
- [ ] Rename any mislabelled `tendency_` variables to `delta_`

closes #41

2023-08-01 15:28 UTC, jatkinson1000 commented
@paogorman I have quick question about the code here.
I have refactored so that the code returns tendencies of variables for use in CAM, rather than updating `t` and `q` internally.
However, the variables `t` and `q` are required to be updated within the physical layer in order to enforce some of the physical constraints (non-negative water content etc).
Are you happy with me saying that we will still use the '`t`' and '`q`' that have been `derived`/converted from CAM variables for this purpose, updating as we enforce various constraints, but these will then be discarded at the end of the subroutine with tendencies returned?

2023-08-01 15:41 UTC, paogorman commented
Yes. I think we will need the updates in t and q internally but we can just forget these between calls to the parameterization.

2023-08-03 13:21 UTC, jatkinson1000 commented
@paogorman 
As part of these changes there are 2 approaches that could be taken:
- a) Pass the entire domain to the parameterisation and get out deltas for all columns.
- b) Loop over the columns calling the parameterisation for each one.

Is there a preferable option?
a) is likely more computationally efficient, but I seem to recall that operating on a 'per column basis' might be an advantage in CAM? Perhaps something @judithberner can help clarify later today?

2023-08-03 14:43 UTC, paogorman commented
I recall the issue is that we ideally want the parameterization to work for both SAM and CAM going forward. SAM works based on (lon,lat,vertical level) whereas CAM has (pcol,level) where pcol is the number of columns. A simple option is to just do one column per call to the parameterization but we will presumably sacrifice computational efficiency. Alternatively we could make pcol the number of grid points in latitude when using the parameterization for SAM and have an outer loop for longitude (or the other way around if it is faster). Something to discuss in the meeting.

2023-08-03 14:47 UTC, jatkinson1000 commented
Haha, yes, I realised shortly before getting this reply that that was an option! 😅 Thanks!

2023-08-03 17:57 UTC, jatkinson1000 commented
Latest commit now has the core parameterisation returning `tendency` (radiative) and `delta`s (advective, autoconversion, sedimentation) for `t` and `q`, as well as the surface sedimentation.
`t`, `q`, and `prec_surf` are now updated in the interface routine.

Data transfer has also been reduced by passing only the part of the column that is operated on by the NN (`1:nrf`) - previously the entire column from the model was passed in).

Care had to be taken when passing `t` and `q` because Fortran is pass by reference and we do not want the semi-updated values returned - instead allocate and make a copy in the routine.

Routine operates on a generic grid as discussed above and in #42 
This involved changing the `y_in` input to be 2-D have a value for each atmospheric column (previously 1-D assuming a lat-lon grid).

2023-08-03 18:03 UTC, jatkinson1000 commented
Given CAM will have no interest in `q` or `t` (as they will be proxys for CAM variables) we could instead perform the allocation and copy in the SAM interface which would avoid wasted allocate and copy operations when running in CAM.

However, this is unlikely to be a bottleneck, and doing this would arguably violate the principle of least surprise should anyone come to re-apply the code somewhere that does deal in `t` and `q` and end up with some double counting.

2023-08-03 18:06 UTC, jatkinson1000 commented
@raehik Would you mind doing a review on this PR?

2023-08-07 14:03 UTC, raehik requested changes
Nice stuff. Couple questions, couple nits, main point on possibly missing final dimension extents when applying tendencies in SAM interface. LGTM otherwise!

2023-08-07 15:57 UTC, jatkinson1000 commented on NN_module/nn_convection_flux.f90
> +        real, intent(in) :: q_0(:, :, :)
A fair point, have moved.
Also added some units, but this has not been fully completed/checked with CamFort. May be worth doing at a later point.

2023-08-07 15:57 UTC, jatkinson1000 commented on NN_module/nn_interface_CAM.f90
> +module nn_interface_SAM_mod
Good catch, have removed and will add into a later PR.

2023-08-07 15:58 UTC, jatkinson1000 commented on NN_module/nn_convection_flux.f90
> +        real, intent(out), dimension(:,:,:) :: t_delta_adv, q_delta_adv, &
Moved as appropriate (with note left to say t_rad_rest_tend is also an output from the NN).

2023-08-07 15:58 UTC, jatkinson1000 commented on NN_module/nn_interface_SAM.f90
> +        real, dimension(nx, ny)      :: prec_sed
Done.

2023-08-07 16:02 UTC, jatkinson1000 commented on NN_module/nn_interface_SAM.f90
> +                                    + t_rad_rest_tend(:,:,:)*dtn
So the previous version of the code passed the entire atmospheric column `(:,:,1:nz)` to the parameterisation, but only updated the lowest `nrf` cells of `t` and `q`.

As a minor improvement whilst refactoring I re-wrote such that the subroutine now takes inputs of size `(:,:,1:nrf)` and returns the same size, thereby reducing some unnecessary operations and arguably improving scientific clarity.

2023-08-07 16:03 UTC, jatkinson1000 commented
Thanks @raehik 
If you are happy with the changes/responses let me know and I'll merge to close.

2023-08-08 12:08 UTC, merged

2023-08-08 12:30 UTC, dorchard commented
lgtm